### PR TITLE
Directly update

### PR DESCRIPTION
**Pull request by adamburkegh**
Beef up and reorganise direct follows calculation

### CODE REVIEW

**Comment by adamburkegh** [comment]
The vispm project HEAD has hidden dependencies on this koalas branch. It adds a bit to the direct follows calculation and breaks the vispm df example in tests/. When I add it in vispm dot charts work for me.

**Comment by AdamBanham** [comment]
the dot charts don't work? with the install on pypi or just with the current head?

**Comment by adamburkegh** [comment]
Latest head. I got it running locally but had to tweak some things and
upgrade to this koalas version

**Comment by AdamBanham** [comment]
I am trending head of vispm as dev, the release version is stable though. Unsure if these changes should be merged to be here or in vispm to be honest

**Comment by adamburkegh** [comment]
Head should never break basic testsOn 30 May 2024, at 7:38 PM, Adam Peter Banham ***@***.***> wrote:﻿
I am treating head of vispm as dev, the release version is stable though. Unsure if these changes should be merged to be here or in vispm to be honest

**Comment by adamburkegh** [comment]
Plus, it's just reorganizing the df calculation, it would be weird in vispm and fits fine here.AdamOn 30 May 2024, at 8:41 PM, Adam Burke ***@***.***> wrote:﻿Head should never break basic testsOn 30 May 2024, at 7:38 PM, Adam Peter Banham ***@***.***> wrote:﻿
I am treating head of vispm as dev, the release version is stable though. Unsure if these changes should be merged to be here or in vispm to be honest

**Comment by AdamBanham** [comment]
I am not sure if these changes I have made, have tests here in koalas. So, before merging I should write some to test the additional steps I have included. 

 vispm doesn't really have tests... more a hobby project than software development. But I should write some tests to ensure that things still produce a figure. Perhaps, I was attempting to be too general in vispm, I was hoping not to need any direct dependency on an event log structure. Instead, I wanted to focus on the behaviour required for the visualisation and use an interceptor based on my required behaviours, i.e. iterating over trace instances.

**Comment by AdamBanham** [comment]
TODOs
- [ ] write some tests
- [ ] merge PR

**Pull request merged**
